[font]
size = 16.0

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[window]
opacity = 0.9

[colors]
transparent_background_colors = false

[colors.primary]
background = "#001419"
foreground = "#839395"

[colors.normal]
black = "#001014"
red = "#db302d"
green = "#849900"
yellow = "#b28500"
blue = "#268bd3"
magenta = "#d23681"
cyan = "#29a298"
white = "#839395"

[colors.bright]
black = "#001014"
red = "#db302d"
green = "#849900"
yellow = "#b28500"
blue = "#268bd3"
magenta = "#d23681"
cyan = "#29a298"
white = "#839395"
