set -g default-terminal tmux-256color
set -as terminal-features ',alacritty:RGB,xterm*:RGB'
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'
set -g extended-keys on
set -g extended-keys-format csi-u

unbind C-b
set -g prefix C-t
set -g repeat-time 500
set -g focus-events on
set -g history-limit 64096
set -sg escape-time 10
set -g set-titles on
set -g set-titles-string '#T'
setw -g mode-keys vi

bind r source-file ~/.config/tmux/tmux.conf \; display 'Reloaded'
bind o run-shell 'open #{q:pane_current_path} 2>/dev/null || xdg-open #{q:pane_current_path}'
bind -r e kill-pane -a
bind g display-popup -d '#{pane_current_path}' -w 80% -h 80% -E lazygit

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -r H resize-pane -L 5
bind -r J resize-pane -D 3
bind -r K resize-pane -U 3
bind -r L resize-pane -R 5

bind | split-window -h
bind - split-window -v
bind x kill-pane
bind X kill-window

source ~/.config/tmux/theme.conf
