set use_preview_script true
set preview_script ~/.config/ranger/scope.sh
set vcs_aware true
set preview_images false
set collapse_preview false
set wrap_plaintext_previews true
set draw_borders both

map uT shell -w trash-restore
